### PR TITLE
add lock to protect action list

### PR DESCRIPTION
**Pull request by gulige**
Found sporadic cases of missing or duplicated message handlings, and fixed it.

### CODE REVIEW

**Comment by alec1o** [comment]
update the "Call" event bridge

**Comment by gulige** [comment]
> 

It doesn't matter. I hope your project will become more and more popular.

**Comment by alec1o** [comment]
1 year after... I'm not sure if my project got popular, but I'm still happy about your help :smiley: @gulige

**Comment by alec1o** [comment]
🫰🏻 Thanks!!! ☺️

**Pull request closed without merging**
